import { Oswald, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from './components/nav'



const oswald = Oswald({
  variable: "--font-oswald",
  subsets: [ "latin" ],
});

const open_sans = Open_Sans({
  variable: "--font-open_sans",
  subsets: [ "latin" ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${oswald.variable} ${open_sans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar/>
        <main>
           {children}
        </main>
      </body>
    </html>
  );
}
